export default [
  {
    name: "TODO Web App",
    img: "/src/assets/frontend/todo.jpg",
    tags: ["html", "css", "react"],
    repo: "https://github.com/Ram0O7/todo-app",
    website: "https://ram0o7.github.io/todo-app/",
  },
  {
    name: "rock-pager-scissors",
    img: "/src/assets/frontend/rock-paper-scissors.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/rock-paper-scissors",
    website: "https://ram0o7.github.io/rock-paper-scissors/",
  },
  {
    name: "sunnyside landing page",
    img: "/src/assets/frontend/sunnyside.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/sunnyside-agency-landing-page",
    website: "https://ram0o7.github.io/sunnyside-agency-landing-page/",
  },
  {
    name: "ecommerce product page",
    img: "/src/assets/frontend/sneakers.jpg",
    tags: ["html", "css", "react"],
    repo: "https://github.com/Ram0O7/ecommerce-product-page",
    website: "https://ram0o7.github.io/ecommerce-product-page/",
  },
  {
    name: "shortly",
    img: "/src/assets/api/shortly.jpg",
    tags: ["html", "css", "react", "api"],
    repo: "https://github.com/Ram0O7/shortly",
    website: "https://ram0o7.github.io/shortly/",
  },
  {
    name: "contries api app",
    img: "/src/assets/api/contries.jpg",
    tags: ["html", "css", "react", "api"],
    repo: "https://github.com/Ram0O7/contries-api-app",
    website: "https://ram0o7.github.io/contries-api-app/",
  },
  {
    name: "news homepage",
    img: "/src/assets/frontend/news-homepage.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/news-homepage",
    website: "https://lucky-yeot-826d87.netlify.app/",
  },
  {
    name: "room homepage",
    img: "/src/assets/frontend/room-homepage.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/room-homepage-master",
    website: "https://ram0o7.github.io/room-homepage-master/",
  },
  {
    name: "chat app illustration",
    img: "/src/assets/frontend/chatApp-illustration.jpg",
    tags: ["html", "css"],
    repo: "https://github.com/Ram0O7/chat-app-css-illustration-master",
    website: "https://ram0o7.github.io/chat-app-css-illustration-master/",
  },
  {
    name: "faq accordian card",
    img: "/src/assets/frontend/faq-accordian.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/faq-accordion-card",
    website: "https://ram0o7.github.io/faq-accordion-card/",
  },
  {
    name: "newsletter sign-up",
    img: "/src/assets/frontend/newsletter-signup.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/newsletter-sign-up-with-success-message-main",
    website:
      "https://ram0o7.github.io/newsletter-sign-up-with-success-message-main/",
  },
];
