export default [
  {
    name: "TODO Web App",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692532806/todo_nwkrmh.jpg",
    tags: ["html", "css", "react"],
    repo: "https://github.com/Ram0O7/todo-app",
    website: "https://ram0o7.github.io/todo-app/",
  },
  {
    name: "rock-pager-scissors",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542593/rock-paper-scissors_dke3a3.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/rock-paper-scissors",
    website: "https://ram0o7.github.io/rock-paper-scissors/",
  },
  {
    name: "sunnyside landing page",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542594/sunnyside_bzbkms.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/sunnyside-agency-landing-page",
    website: "https://ram0o7.github.io/sunnyside-agency-landing-page/",
  },
  {
    name: "ecommerce product page",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542594/sneakers_ts2dwn.jpg",
    tags: ["html", "css", "react"],
    repo: "https://github.com/Ram0O7/ecommerce-product-page",
    website: "https://ram0o7.github.io/ecommerce-product-page/",
  },
  {
    name: "shortly",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692543082/shortly_zhmanx.jpg",
    tags: ["html", "css", "react", "api"],
    repo: "https://github.com/Ram0O7/shortly",
    website: "https://ram0o7.github.io/shortly/",
  },
  {
    name: "contries api app",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692543081/contries_wmb2hm.jpg",
    tags: ["html", "css", "react", "api"],
    repo: "https://github.com/Ram0O7/contries-api-app",
    website: "https://ram0o7.github.io/contries-api-app/",
  },
  {
    name: "news homepage",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542594/news-homepage_pcnk7w.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/news-homepage",
    website: "https://lucky-yeot-826d87.netlify.app/",
  },
  {
    name: "room homepage",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542594/room-homepage_iy0c7m.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/room-homepage-master",
    website: "https://ram0o7.github.io/room-homepage-master/",
  },
  {
    name: "chat app illustration",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542593/chatApp-illustration_s7y4sc.jpg",
    tags: ["html", "css"],
    repo: "https://github.com/Ram0O7/chat-app-css-illustration-master",
    website: "https://ram0o7.github.io/chat-app-css-illustration-master/",
  },
  {
    name: "faq accordian card",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542593/faq-accordian_vgafsb.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/faq-accordion-card",
    website: "https://ram0o7.github.io/faq-accordion-card/",
  },
  {
    name: "newsletter sign-up",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692542593/newsletter-signup_rhqgtn.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/newsletter-sign-up-with-success-message-main",
    website:
      "https://ram0o7.github.io/newsletter-sign-up-with-success-message-main/",
  },
  {
    name: "calculator",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692544150/calculator_uyislm.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/calculator-app",
    website: "https://ram0o7.github.io/calculator-app/",
  },
  {
    name: "tip calculator",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692544187/tip-calculator_otuvxf.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/tip-calculator-app",
    website: "https://ram0o7.github.io/tip-calculator-app/",
  },
  {
    name: "advice generator app",
    img: "https://res.cloudinary.com/dn6bzdlno/image/upload/v1692544151/advice-generator_wctzzd.jpg",
    tags: ["html", "css", "javascript"],
    repo: "https://github.com/Ram0O7/advice-generator-app-main",
    website: "https://ram0o7.github.io/advice-generator-app-main/",
  },
];
